# Generated by Django 4.2.6 on 2023-10-18 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_countries', '0005_remove_hostcountriesmodels_stadiums'),
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumsmodels',
            name='host_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='host_countries.hostcountriesmodels'),
        ),
    ]
