# Generated by Django 4.2.6 on 2023-10-10 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldCupEditionsModel',
            fields=[
                ('id', models.UUIDField(db_column='ID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('year', models.DateField(verbose_name='%d/%m/%Y')),
                ('winner', models.CharField(choices=[('Brazil', 'Brazil'), ('Germany', 'Germany'), ('Italy', 'Italy'), ('Argentina', 'Argentina'), ('France', 'France'), ('Spain', 'Spain'), ('England', 'England'), ('Uruguay', 'Uruguay')], max_length=10)),
                ('edition_number', models.IntegerField()),
                ('mvp', models.CharField(max_length=50)),
            ],
        ),
    ]
