# Generated by Django 4.2.6 on 2023-10-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host_countries', '0003_alter_hostcountriesmodels_name'),
        ('editions', '0002_worldcupeditionsmodel_stadiums'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupeditionsmodel',
            name='host_countries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='host_countries.hostcountriesmodels', to_field='name'),
        ),
    ]
