# Generated by Django 4.2.6 on 2023-10-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0005_alter_worldcupeditionsmodel_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldcupeditionsmodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
