# Generated by Django 4.2.6 on 2023-10-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('national_teams', '0001_initial'),
        ('editions', '0006_worldcupeditionsmodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldcupeditionsmodel',
            name='national_teams',
        ),
        migrations.AddField(
            model_name='worldcupeditionsmodel',
            name='national_teams',
            field=models.ManyToManyField(blank=True, null=True, to='national_teams.nationalteamsmodels'),
        ),
    ]
