# Generated by Django 4.2.6 on 2023-10-22 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0007_remove_worldcupeditionsmodel_national_teams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldcupeditionsmodel',
            name='national_teams',
        ),
        migrations.RemoveField(
            model_name='worldcupeditionsmodel',
            name='stadiums',
        ),
    ]
