# Generated by Django 4.2.6 on 2023-10-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
        ('host_countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcountriesmodels',
            name='stadiums',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stadiums.stadiumsmodels'),
        ),
    ]
