# Generated by Django 4.2.6 on 2023-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host_countries', '0002_hostcountriesmodels_stadiums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcountriesmodels',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
