# Generated by Django 4.2.6 on 2023-10-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadiums', '0001_initial'),
        ('host_countries', '0003_alter_hostcountriesmodels_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostcountriesmodels',
            name='stadiums',
        ),
        migrations.AddField(
            model_name='hostcountriesmodels',
            name='stadiums',
            field=models.ManyToManyField(null=True, to='stadiums.stadiumsmodels'),
        ),
    ]
