# Generated by Django 4.2.6 on 2023-10-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalTeamsModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('year', models.DateField(verbose_name='%d/%m/%Y')),
                ('world_cups', models.IntegerField()),
                ('players', models.JSONField()),
            ],
        ),
    ]
