# Generated by Django 4.2.6 on 2023-10-22 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0008_remove_worldcupeditionsmodel_national_teams_and_more'),
        ('national_teams', '0002_alter_nationalteamsmodels_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationalteamsmodels',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='editions.worldcupeditionsmodel'),
        ),
    ]
